### ISSUE TITLE
No Support for WatchOS

### ISSUE THREAD

**Issue by dehydratedpotato** [phatblat/WebView#1]
Hey there!

Just filing an issue regarding platform support...
Your README said this package works on all Apple Platforms, and you put **WatchOS 6.0** as a requirement... But upon testing, this package does not seem to work with watchOS -- due to the use of WebKit in this packages source, and the lack of dev access to the `WebKit` API within WatchOS. _When trying to use this package with a watchOS app, Xcode starts spitting errors!_

Mostly trying to bring awareness to the issue, but also seeing if you knew any way to work around this...Like, a way to still be able to use a webView in a watchOS app?

**Hope all is well! Good day!** 😊

**Comment by phatblat** [comment]
Great point and sorry for the misleading info on the README. I had started this project remembering something about web support on watchOS and tvOS. However, the WWDC 2018 [Designing Web Content for watchOS](https://developer.apple.com/videos/play/wwdc2018/239) video that I was thinking of very clearly calls out that this is only supported in the Apple Messages and Mail apps 😔.

Over on tvOS, I recall hearing about webview support, but it turns out that it was actually `UIWebView` and it's a private API so nothing that can be used in an app headed to the app store. (see [tvOSBrowser](https://github.com/steventroughtonsmith/tvOSBrowser))
